/*
 * WaveSpeed AI API
 * API for generating images using WaveSpeed AI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.wavespeed.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PredictionUrls
 */
public class PredictionUrlsTest {
    private final PredictionUrls model = new PredictionUrls();

    /**
     * Model tests for PredictionUrls
     */
    @Test
    public void testPredictionUrls() {
        // TODO: test PredictionUrls
    }

    /**
     * Test the property 'get'
     */
    @Test
    public void getTest() {
        // TODO: test get
    }

}
